menu:
- {name: 'Research', url: '/research'}
- {name: 'People', url: '/people'}
- {name: 'Publications', url: '/publications'}
- {name: 'Opportunities', url: '/opportunities'}
- {name: 'Contact', url: '/contact'}

people:
- {name: 'Javier López Garrido', title: 'Principal Investigator', role: 'The Grandmaster', research: 'Evolutionary Cell Biology of Bacillus Subtilis', email: 'lopezgarrido@evolbio.mpg.de', image: 'assets/img/Javi.jpg', url: 'javi'}
- {name: 'Alan Derman', title: 'Senior Scientist', role: 'The Knower', email: 'derman@evolbio.mpg.de', research: 'Evolutionary Cell Biology of Bacillus Subtilis', image: 'assets/img/Alan.jpg', url: 'alan'}
- {name: 'Nadja Hüttman', title: 'Lab Technician', role: 'The Solver', email: 'nhuettman@evolbio.mpg.de', research: 'Genetic and physiological regulation in Bacillus Subtilis', image: 'assets/img/Nadja.jpg', url: 'nadja'}
- {name: 'Deniz Akbulut', title: 'Research assistant', role: 'The Profiler', email: 'akbulut@evolbio.mpg.de', research: 'Metabolism of Bacillus subtilis', image: 'assets/img/Deniz.jpg', url: 'deniz'}
- {name: 'Alejandro Bonive Boscan', title: 'Doctoral Researcher', role: 'The Synthetizer', email: 'bonive@evolbio.mpg.de', research: 'Protein co-option in Bacillus subtilis', image: 'assets/img/Alejandro.jpg', url: 'alejandro'}
- {name: 'Iqra Kasu', title: 'Doctoral Researcher', role: 'The Metabolizer', email: 'kasu@evolbio.mpg.de', research: 'Metabolism governing spore revival', image: 'assets/img/Iqra.jpg', url: 'iqra'}
- {name: 'Octavio Reyes Matte', title: 'Doctoral Researcher', role: 'The Programmer', email: 'reyesmatte@evolbio.mpg.de', research: 'Evolutionary Cell Biohysics', image: 'assets/img/Octavio.jpg', url: 'octavio'}
- {name: 'Corinna Schwarz', title: 'Doctoral Researcher', role: 'The Evolver', email: 'coschwarz@evolbio.mpg.de', research: 'Evolutionary approaches to Sporulation', image: 'assets/img/Corinna.jpg', url: 'corinna'}
- {name: 'Felipe Sinhorini', title: 'Lab Technician', role: 'The Maintainer', email: 'sinhorini@evolbio.mpg.de', research: 'General lab maintenance and functionality', image: 'assets/img/Felipe.jpg', url: 'felipe'}

research:
- {name: 'Metabolism', url: 'metabolism'}
- {name: 'Evolution', url: 'evolution'}
- {name: 'Cell shape', url: 'cellshape'}


social:
- {icon: 'world', link: 'https://www.evolbio.mpg.de/3360782/evolcellbiol'}
- {icon: 'github', link: 'https://github.com/lopezgarridolab'}
- {icon: 'twitter', link: 'https://twitter.com/LopezGarridoLab'}

contacts:
- {name: 'Javier López Garrido', position: 'Max Planck Research Group Leader', group: 'Research Group Evolutionary Cell Biology', institution: 'Max Planck Institute for Evolutionary Biology', institution_address: 'August Thienemann Strasse 2, Plön, Germany', email: 'lopezgarrido@evolbio.mpg.de', image: 'assets/img/mpi-plon.jpg'}
